version: '3.2'
services:
  nginx:
    image: nginx:stable
    volumes:
      - './development-nginx.conf:/etc/nginx/conf.d/default.conf'
    ports:
      - 8888:80
  frontend:
    image: node:current
    volumes:
      - type: bind
        source: ./frontend
        target: /opt/frontend
      - type: bind
        source: ../bitbloq/packages/ui
        target: /opt/ui
      - /opt/frontend/node_modules/
    expose:
      - 8000
    ports:
      - 8000:8000
    command: >
      bash -c "cd /opt/frontend
      && rm -R node_modules/@bitbloq
      && npm install
      && npm link ../ui
      && npm run develop"


