version: '3.2'

services:

  nginx:
    image: nginx:stable
    volumes:
      - './development-nginx.conf:/etc/nginx/conf.d/default.conf'
    depends_on:
      - frontend
      - api
    ports:
      - 8000:80

  frontend:
    image: node:current
    volumes:
      - type: bind
        source: ../bitbloq
        target: /opt/bitbloq
      - type: bind
        source: ./frontend
        target: /opt/frontend
    command: >
      bash -c "mkdir -p /opt/build/
      && cd /opt/bitbloq
      && cp -r `ls -A | grep -v 'node_modules' | grep -v 'packages'` /opt/build
      && mkdir -p /opt/build/packages/3d
      && cd /opt/bitbloq/packages/3d
      && cp -r `ls -A | grep -v 'node_modules' | grep -v 'src'` /opt/build/packages/3d
      && ln -sf /opt/bitbloq/packages/3d/src /opt/build/packages/3d/
      && mkdir -p /opt/build/packages/bloqs
      && cd /opt/bitbloq/packages/bloqs
      && cp -r `ls -A | grep -v 'node_modules' | grep -v 'src'` /opt/build/packages/bloqs
      && ln -sf /opt/bitbloq/packages/bloqs/src /opt/build/packages/bloqs/
      && mkdir -p /opt/build/packages/junior
      && cd /opt/bitbloq/packages/junior
      && cp -r `ls -A | grep -v 'node_modules' | grep -v 'src'` /opt/build/packages/junior
      && ln -sf /opt/bitbloq/packages/junior/src /opt/build/packages/junior/
      && mkdir -p /opt/build/packages/lib3d
      && cd /opt/bitbloq/packages/lib3d
      && cp -r `ls -A | grep -v 'node_modules' | grep -v 'src'` /opt/build/packages/lib3d
      && ln -sf /opt/bitbloq/packages/lib3d/src /opt/build/packages/lib3d/
      && mkdir -p /opt/build/packages/ui
      && cd /opt/bitbloq/packages/ui
      && cp -r `ls -A | grep -v 'node_modules' | grep -v 'src'` /opt/build/packages/ui
      && ln -sf /opt/bitbloq/packages/ui/src /opt/build/packages/ui/
      && mkdir -p /opt/build/packages/frontend
      && cd /opt/frontend
      && cp -r `ls -A | grep -v 'node_modules' | grep -v 'src'` /opt/build/packages/frontend
      && ln -sf /opt/frontend/src /opt/build/packages/frontend/
      && cd /opt/build
      && npm install
      && npx lerna bootstrap
      && cd /opt/build/packages/frontend
      && npm run develop"

  api:
    image: node:current
    environment:
      - MONGO_URL=mongodb://mongodb/bitbloq_space
      - JWT_SECRET=supersecretpassword
      - PORT=8000
      - GOOGLE_APPLICATION_CREDENTIALS=/google-application-credentials.json
      - REDIS_DOMAIN_NAME=redis
      - REDIS_PORT_NUMBER=6379
    depends_on:
      - mongodb
      - redis
    volumes:
      - type: bind
        source: ./api
        target: /opt/api
      - type: bind
        source: "${GOOGLE_APPLICATION_CREDENTIALS}"
        target: /google-application-credentials.json
      - /opt/api/node_modules/
      - /opt/api/.cache/
    ports:
      - 8002:8000
      - 9229:9229
    command: >
      bash -c "cd /opt/api
      && npm install
      && npm run dev-inspect"

  redis:
    image: redis:latest

  mongodb:
    image: mongo:latest
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    ports:
      - 8001:27017
    command: mongod --smallfiles --logpath=/dev/null


