version: '3.2'

services:

  nginx:
    image: nginx:stable
    volumes:
      - './development-nginx.conf:/etc/nginx/conf.d/default.conf'
    depends_on:
      - frontend
      - api
    ports:
      - 8000:80

  frontend:
    image: node:current
    volumes:
      - type: bind
        source: ./frontend
        target: /opt/frontend
      - type: bind
        source: ../bitbloq/packages/ui
        target: /opt/ui
      - type: bind
        source: ../bitbloq/packages/3d
        target: /opt/3d
      - type: bind
        source: ../bitbloq/packages/lib3d
        target: /opt/lib3d
      - /opt/frontend/node_modules/
      - /opt/frontend/public/
      - /opt/frontend/.cache/
      - /opt/ui/node_modules/
      - /opt/3d/node_modules/
      - /opt/lib3d/node_modules/
    command: >
      bash -c "cd /opt/frontend
      && rm -Rf node_modules/@bitbloq
      && npm install
      && npm link ../ui
      && npm link ../lib3d
      && npm link ../3d
      && npm run develop"

  api:
    image: node:current
    environment:
      - MONGO_URL=mongodb://mongodb/bitbloq_space
    depends_on:
      - mongodb
    volumes:
      - type: bind
        source: ./api
        target: /opt/api
      - /opt/api/node_modules/
    command: >
      bash -c "cd /opt/api
      && npm install
      && npm run dev"

  mongodb:
    image: mongo:latest
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    ports:
      - 8001:27017
    command: mongod --smallfiles --logpath=/dev/null


