version: '3.2'

services:

  nginx:
    image: nginx:stable
    volumes:
      - './development-nginx.conf:/etc/nginx/conf.d/default.conf'
    depends_on:
      - frontend
      - api
    ports:
      - 8000:80

  frontend:
    image: node:current
    volumes:
      - type: bind
        source: ../bitbloq
        target: /home/alda/Documentos/bitbloq3/install-bitbloq/opt/bitbloq
      - type: bind
        source: ./frontend
        target: /home/alda/Documentos/bitbloq3/install-bitbloq/opt/frontend
      - /home/alda/Documentos/bitbloq3/install-bitbloq/opt/frontend/node_modules/
      - /home/alda/Documentos/bitbloq3/install-bitbloq/opt/frontend/public/
      - /home/alda/Documentos/bitbloq3/install-bitbloq/opt/frontend/.cache/
      - /home/alda/Documentos/bitbloq3/install-bitbloq/opt/bitbloq/node_modules/
      - /home/alda/Documentos/bitbloq3/install-bitbloq/opt/bitbloq/packages/ui/node_modules/
      - /home/alda/Documentos/bitbloq3/install-bitbloq/opt/bitbloq/packages/3d/node_modules/
      - /home/alda/Documentos/bitbloq3/install-bitbloq/opt/bitbloq/packages/lib3d/node_modules/
      - /home/alda/Documentos/bitbloq3/install-bitbloq/opt/bitbloq/packages/bloqs/node_modules/
      - /home/alda/Documentos/bitbloq3/install-bitbloq/opt/bitbloq/packages/junior/node_modules/
    command: >
      bash -c "cd /home/alda/Documentos/bitbloq3/install-bitbloq/opt/frontend
      && rm -Rf /home/alda/Documentos/bitbloq3/install-bitbloq/opt/frontend/node_modules/@bitbloq
      && npm install
      && npm link ../bitbloq/packages/ui
      && npm link ../bitbloq/packages/3d
      && npm link ../bitbloq/packages/lib3d
      && npm link ../bitbloq/packages/bloqs
      && npm link ../bitbloq/packages/junior
      && cd /home/alda/Documentos/bitbloq3/install-bitbloq/opt/bitbloq
      && npm install
      && npx lerna bootstrap
      && cd /home/alda/Documentos/bitbloq3/install-bitbloq/opt/frontend
      && npm run develop"

  api:
    image: node:current
    environment:
      - MONGO_URL=mongodb://mongodb/bitbloq_space
      - JWT_SECRET=supersecretpassword
      - PORT=8000
      - GOOGLE_APPLICATION_CREDENTIALS=/google-application-credentials.json
      - REDIS_DOMAIN_NAME=redis
      - REDIS_PORT_NUMBER=6379
      - USE_REDIS=false
    depends_on:
      - mongodb
      - redis
    volumes:
      - type: bind
        source: ./api
        target: /home/alda/Documentos/bitbloq3/install-bitbloq/opt/api
      - type: bind
        source: "${GOOGLE_APPLICATION_CREDENTIALS}"
        target: /google-application-credentials.json
      - /home/alda/Documentos/bitbloq3/install-bitbloq/opt/api/node_modules/
      - /home/alda/Documentos/bitbloq3/install-bitbloq/opt/api/.cache/
    ports:
      - 8002:8000
      - 9229:9229
    command: >
      bash -c "cd /home/alda/Documentos/bitbloq3/install-bitbloq/opt/api
      && npm install
      && npm run dev-inspect"

  redis:
    image: redis:latest

  mongodb:
    image: mongo:latest
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    ports:
      - 8001:27017
    command: mongod --smallfiles --logpath=/dev/null


